"""Microsoft Word (.docx) export formatter."""

from __future__ import annotations

from pathlib import Path

from bits_whisperer.core.job import TranscriptionResult
from bits_whisperer.export.base import ExportFormatter, format_timestamp


class WordFormatter(ExportFormatter):
    """Export transcript as a Word document using python-docx."""

    @property
    def format_id(self) -> str:
        return "docx"

    @property
    def display_name(self) -> str:
        return "Microsoft Word (.docx)"

    @property
    def file_extension(self) -> str:
        return ".docx"

    def export(
        self,
        result: TranscriptionResult,
        output_path: str | Path,
        include_timestamps: bool = True,
        include_speakers: bool = True,
        include_confidence: bool = False,
    ) -> Path:
        """Export transcript as a .docx file.

        Args:
            result: Transcription data.
            output_path: Destination file path.
            include_timestamps: Include timestamps per segment.
            include_speakers: Include speaker labels.
            include_confidence: Include confidence percentages.

        Returns:
            Path to the written file.
        """
        try:
            from docx import Document
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            from docx.shared import Pt, RGBColor
        except ImportError as exc:
            raise ImportError(
                "python-docx is required for Word export. "
                "Install it with: pip install python-docx"
            ) from exc

        output_path = Path(output_path)
        doc = Document()

        # -- Title page --
        title = doc.add_heading("Transcript", level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run(result.audio_file)
        run.font.size = Pt(14)
        run.font.color.rgb = RGBColor(0, 0x78, 0xD4)

        # -- Metadata table --
        table = doc.add_table(rows=5, cols=2, style="Light Shading Accent 1")
        _meta_row(table, 0, "Provider", result.provider)
        _meta_row(table, 1, "Model", result.model)
        _meta_row(table, 2, "Language", result.language)
        _meta_row(table, 3, "Duration", format_timestamp(result.duration_seconds))
        _meta_row(table, 4, "Date", result.created_at)

        doc.add_paragraph()  # spacer

        # -- Transcript body --
        doc.add_heading("Transcript", level=1)

        if result.segments:
            current_speaker: str | None = None
            for seg in result.segments:
                if include_speakers and seg.speaker and seg.speaker != current_speaker:
                    current_speaker = seg.speaker
                    speaker_para = doc.add_heading(seg.speaker, level=2)
                    for run in speaker_para.runs:
                        run.font.size = Pt(13)

                para = doc.add_paragraph()
                if include_timestamps:
                    ts_run = para.add_run(
                        f"[{format_timestamp(seg.start)} — {format_timestamp(seg.end)}]  "
                    )
                    ts_run.font.size = Pt(9)
                    ts_run.font.color.rgb = RGBColor(0x00, 0x78, 0xD4)

                text_run = para.add_run(seg.text)
                text_run.font.size = Pt(11)

                if include_confidence and seg.confidence > 0:
                    conf_run = para.add_run(f"  ({seg.confidence:.0%})")
                    conf_run.font.size = Pt(8)
                    conf_run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)
        else:
            doc.add_paragraph(result.full_text)

        # -- Footer --
        footer_section = doc.sections[0]
        footer = footer_section.footer
        footer_para = footer.paragraphs[0]
        footer_para.text = "Generated by BITS Whisperer"
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.save(str(output_path))
        return output_path


def _meta_row(table, row_idx: int, label: str, value: str) -> None:
    """Fill a metadata table row."""
    table.cell(row_idx, 0).text = label
    table.cell(row_idx, 1).text = value
