from typing import Any, Dict, Optional, Protocol

class _RawOutputStream(Protocol):
    def __enter__(self) -> "_RawOutputStream": ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def write(self, data: bytes) -> None: ...

class RawOutputStream:
    def __init__(
        self,
        *,
        samplerate: int,
        channels: int,
        dtype: str,
    ) -> None: ...
    def __enter__(self) -> _RawOutputStream: ...
    def __exit__(self, exc_type, exc, tb) -> None: ...


def query_devices(device: Optional[int] = None, kind: str = "") -> Dict[str, Any]: ...
